### ISSUE TITLE
Spectrum Gap issue

### ISSUE THREAD

**Issue by LikesTrash** [KawaiiWafu/osbpy#1] opened 2019-05-05 05:01 UTC
While calling on Spectrum, gap was defined as a string instead of an integer.
![cap](https://user-images.githubusercontent.com/15986525/57188696-c3436800-6ec8-11e9-9639-d02e01c3cb69.PNG)

I tried defining gap as 0, it worked but turns out that posy was also recognized as a string. ![cap](https://media.discordapp.net/attachments/570829031130529812/574462912035291137/unknown.png?width=1442&height=139)

Also is bar_file supposed to be there? It would mess up __init__ wouldn't it? It wouldn't make sense for bar_file to be path, would it? If it was for bar_file to be path then origin would end up becoming a integer instead of a string.
![cap](https://media.discordapp.net/attachments/570829031130529812/574461652435599360/unknown.png)

**Comment by KawaiiWafu** [comment] 2019-05-06 08:54
I will definitely check this more thoroughly when I decide to comeback to osbpy development (don't worry, it's not dead)

However, I'm just thinking you're entering wrong parameters.
![image](https://user-images.githubusercontent.com/11209667/57214740-2e855b00-6feb-11e9-8093-e75b6e96f6ec.png)
The red parameter is supposed to be a gap, not arrange parameter. You ignored the bar_file completely, so obviously the function will crash.

bar_file is a relative path. That means if you use just "bar.png", it will take that file from your map's folder. You can also do "images/bar.png" (or "images\\bar.png") and it will still take the file from map's folder.

I'm not sure why you think origin would end up being an integer. Python doesn't have predefined data types, so whatever you enter is the data type that the function will accept.
I suggest you to take a look at [unfinished wiki](https://osbpy.readthedocs.io/en/latest/reference.html#spectrum), if I was unclear.

Contact me in case I'm missing something or something is not clear. I'm willing to fix any issues and I still plan on improving osbpy. Next update should improve the errors, so that the user knows better where an issue happened.

**Comment by KawaiiWafu** [comment] 2019-10-04 14:57
Closing, no further input and seems to be working as intended.

**Closed by KawaiiWafu** 2019-10-04 14:57 UTC
